from django.contrib import admin
from . models import *

admin.site.register(Banner) 
admin.site.register(Room)
admin.site.register(About)
admin.site.register(Service)
admin.site.register(Blog)
admin.site.register(Gallery)
admin.site.register(Dining)
admin.site.register(Spa)
admin.site.register(Meeting)
admin.site.register(Ourservice)
admin.site.register(Whoweare)
admin.site.register(Ourinfo)
admin.site.register(Ourservice1)
admin.site.register(Contact)
admin.site.register(Comfort)
admin.site.register(Customer)
admin.site.register(Cart)
admin.site.register(CartRoom)
admin.site.register(Bookings)
