# Generated by Django 4.1.7 on 2023-03-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomtmg4',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 11, 8, 49, 115851)),
        ),
    ]
