# Generated by Django 3.2.5 on 2023-04-17 12:17

import ckeditor.fields
import datetime
from django.db import migrations, models
import eagles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eagles', '0007_booking_address_alter_blog_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[eagles.validators.Banner_v])),
                ('button', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 13, 17, 50, 262614)),
        ),
    ]
