# Generated by Django 3.2.5 on 2023-04-17 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eagles', '0008_auto_20230417_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discount', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('booking_status', models.CharField(choices=[('Booking Received', 'Booking Received'), ('Booking Processing', 'Booking Processing'), ('Booking Completed', 'Booking Completed'), ('Booking Canceled', 'Booking Canceled')], max_length=200)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Paystack', 'Paystack'), ('Payment Transfer', 'Payment Transfer'), ('Cash On Arrival', 'Cash On Delivery')], default='Paystack', max_length=20)),
                ('payment_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Bookings',
                'verbose_name_plural': 'Bookings',
                'db_table': 'Bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eagles.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='room',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 23, 23, 368666)),
        ),
        migrations.AddField(
            model_name='cartroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eagles.room'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eagles.customer'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eagles.cart'),
        ),
    ]
