# Generated by Django 4.1.7 on 2023-04-18 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagles', '0010_auto_20230417_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 6, 3, 6, 356001)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Payment Transfer', 'Payment Transfer'), ('Cash On Arrival', 'Cash On Arrival')], default='Paystack', max_length=20),
        ),
    ]
