# Generated by Django 4.1.7 on 2023-04-19 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagles', '0012_video_alter_blog_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 6, 58, 55, 3877)),
        ),
    ]
